baseURL = "https://cityinthesky.co.uk/"
languageCode = "en-gb"
title = "David A W Barton"
description = "Personal webpage of David A W Barton"
theme = "PaperMod"

[params]
DateFormat = "2006-01-02"
ShowCodeCopyButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
mainSections = ["posts"]

[params.profileMode]
enabled = true
title = "David A W Barton"
subtitle = """
*Professor of Computional and Experimental Mathematics*

Researcher, Teacher, Open Source Developer, Christian
"""
imageUrl = "about-me/DavidBarton-square.jpg"
imageTitle = "A picture of David A W Barton"
imageWidth = 200
imageHeight = 200

[[params.socialIcons]]
name = "email"
url = "mailto:barton@cityinthesky.co.uk"

[[params.socialIcons]]
name = "github"
url = "https://github.com/dawbarton/"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/davidawbarton/"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/david-barton-61822443/"

[privacy.youtube]
privacyEnhanced = true

[privacy.twitter]
enableDNT = true
simple = true

[services.twitter]
disableInlineCSS = true

[privacy.vimeo]
enableDNT = true
simple = true

[[menu.main]]
name = "About"
url = "/about-me/"
weight = 10

[[menu.main]]
name = "Research"
url = "/research/"
weight = 20

[[menu.main]]
name = "Open source"
url = "/opensource/"
weight = 30

[[menu.main]]
name = "Christianity"
url = "/christianity/"
weight = 40

[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 15
