baseURL = "https://cityinthesky.co.uk/"
languageCode = "en-gb"
title = "David A W Barton"
description = "Personal webpage of David A W Barton"
theme = "PaperMod"

[params]
DateFormat = "2006-01-02"
ShowCodeCopyButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
mainSections = ["posts"]

[params.profileMode]
enabled = true
title = "David A W Barton"
subtitle = """
**_Professor of Computational and Experimental Mathematics_**

[University of Bristol](https://www.bristol.ac.uk/)

Nonlinear dynamics &nbsp;&bull;&nbsp; Scientific machine learning &nbsp;&bull;&nbsp; Scientific computing

[**Research**](/research/) &nbsp;&bull;&nbsp; [**PhD opportunities**](/research/phd-projects/) &nbsp;&bull;&nbsp; [**Collaborations**](/research/new-researchers/)
"""
imageUrl = "about-me/DavidBarton-square.jpg"
imageTitle = "A picture of David A W Barton"
imageWidth = 200
imageHeight = 200

[[params.socialIcons]]
name = "email"
url = "mailto:david.barton@bristol.ac.uk"

[[params.socialIcons]]
name = "github"
url = "https://github.com/dawbarton/"

[[params.socialIcons]]
name = "googlescholar"
url = "https://scholar.google.com/citations?hl=en&user=9lxSeYMAAAAJ"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/david-barton-61822443/"

[privacy.youtube]
privacyEnhanced = true

[privacy.vimeo]
enableDNT = true
simple = true

[[menu.main]]
name = "About"
url = "/about-me/"
weight = 10

[[menu.main]]
name = "Research"
url = "/research/"
weight = 15

[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 25

[[menu.main]]
name = "Open source"
url = "/opensource/"
weight = 30

[[menu.main]]
name = "Christianity"
url = "/christianity/"
weight = 40
